const KEY='readingAdventureV1';
const DEFAULT={name:'Reader',pin:'2468',benchmarked:false,day:0,xp:0,streak:0,history:[],skills:{decoding:50,morphology:50,fluency:50,vocabulary:50,literal:50,inference:50,gist:50},errors:{},interests:['animals','mysteries','science']};
let S=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(DEFAULT); let session={score:0,total:0,results:[]};
const $=s=>document.querySelector(s), save=()=>localStorage.setItem(KEY,JSON.stringify(S));
function shell(html){$('#app').innerHTML=`<div class="wrap">${html}</div>`}
function home(){shell(`<section class="hero"><div>📚✨</div><h1>Reading Adventure</h1><p class="sub">Train your reading powers. Unlock stronger skills every day.</p>${!S.benchmarked?`<button class="btn" onclick="benchmarkIntro()">Start My Reading Power Check</button>`:`<button class="btn" onclick="daily()">▶ Start Today's Mission</button>`}<button class="btn secondary" onclick="parentGate()">🔒 Parent Dashboard</button></section>${S.benchmarked?`<section class="card"><div class="grid"><div class="stat"><span>Mission Days</span><b>${S.day}</b></div><div class="stat"><span>XP</span><b>${S.xp}</b></div><div class="stat"><span>Current Streak</span><b>${S.streak}</b></div><div class="stat"><span>Focus Skill</span><b style="font-size:1rem">${weakest()}</b></div></div></section>`:''}`)}
const BANK={decoding:[['Which word has 3 syllables?',['basket','remember','plant','shine'],1],['Choose the best split for fantastic.',['fan-tas-tic','fant-ast-ic','fa-ntas-tic'],0],['Which word is easiest to decode as re + play?',['reply','replay','really'],1]],morphology:[['What does the prefix un- usually mean?',['again','not','before'],1],['In disagreement, which part means “not/opposite”?',['dis-','agree','-ment'],0],['What does -less mean in fearless?',['full of','without','again'],1]],vocabulary:[['If a trail is treacherous, it is probably…',['dangerous','tiny','famous'],0],['A reluctant person is…',['eager','unwilling','noisy'],1],['If something is scarce, there is…',['plenty','very little','exactly enough'],1]],literal:[['Maya packed a flashlight before entering the cave. What did Maya pack?',['a rope','a flashlight','a map'],1]],inference:[['Leo kept looking at the dark clouds and hurried to bring the bikes inside. What can you infer?',['He expects rain','He lost a bike','He wants to ride'],0]],gist:[['Bees carry pollen between flowers. This helps many plants make seeds and fruit. What is the gist?',['Bees help plants reproduce','Bees eat fruit','Flowers avoid bees'],0]]};
function benchmarkIntro(){shell(`<section class="hero"><h1>Reading Power Check</h1><p class="sub">This finds your strongest reading powers and the ones we're going to train. It is okay not to know an answer.</p><button class="btn" onclick="runBenchmark()">I'm Ready</button></section>`)}
function runBenchmark(){session={score:0,total:0,results:[]}; let qs=[]; Object.entries(BANK).forEach(([skill,arr])=>arr.forEach(q=>qs.push({skill,q}))); askSequence(qs,0,true)}
function askSequence(qs,i,isBench){if(i>=qs.length){return isBench?finishBenchmark():finishDaily()} let {skill,q}=qs[i]; let [prompt,opts,ans]=q; shell(`<section class="card"><div class="small">${isBench?'Reading Power Check':'Today’s Mission'} • ${i+1}/${qs.length}</div><div class="bar"><i style="width:${(i/qs.length)*100}%"></i></div><h2>${prompt}</h2>${opts.map((o,j)=>`<button class="btn choice" onclick="answer(${j},${ans},'${skill}',${i},${isBench})">${o}</button>`).join('')}</section>`); window._qs=qs}
function answer(choice,ans,skill,i,isBench){let ok=choice===ans; session.total++; if(ok)session.score++; session.results.push({skill,ok}); askSequence(window._qs,i+1,isBench)}
function finishBenchmark(){let groups={};session.results.forEach(r=>(groups[r.skill]??=[]).push(r.ok));Object.entries(groups).forEach(([k,a])=>S.skills[k]=Math.round(35+55*(a.filter(Boolean).length/a.length)));S.skills.fluency=50;S.benchmarked=true;S.day=0;save();shell(`<section class="hero"><h1>Power Check Complete 🎉</h1><p class="sub">I found where to start. Your daily missions will adjust as you improve.</p><button class="btn" onclick="home()">See My Adventure</button></section>`)}
function weakest(){return Object.entries(S.skills).sort((a,b)=>a[1]-b[1])[0][0].replace(/^./,c=>c.toUpperCase())}
function daily(){session={score:0,total:0,results:[]};let ranked=Object.entries(S.skills).sort((a,b)=>a[1]-b[1]).map(x=>x[0]);let qs=[];ranked.slice(0,3).forEach(skill=>(BANK[skill]||BANK.decoding).slice(0,2).forEach(q=>qs.push({skill,q}))); qs.push({skill:'inference',q:BANK.inference[0]},{skill:'gist',q:BANK.gist[0]}); askSequence(qs,0,false)}
function finishDaily(){let groups={};session.results.forEach(r=>(groups[r.skill]??=[]).push(r.ok));Object.entries(groups).forEach(([k,a])=>{let pct=a.filter(Boolean).length/a.length;S.skills[k]=Math.max(0,Math.min(100,Math.round(S.skills[k]+(pct-.55)*8))) });let pct=Math.round(100*session.score/session.total);S.day++;S.xp+=session.score*10;S.streak=pct>=70?S.streak+1:0;S.history.push({date:new Date().toISOString(),day:S.day,pct,skills:structuredClone(S.skills)});save();shell(`<section class="hero"><h1>Mission Complete 🚀</h1><div class="word">${pct}%</div><p>You earned <b>${session.score*10} XP</b>.</p><p>Tomorrow's mission will put extra practice where you need it most.</p><button class="btn" onclick="home()">Finish</button></section>`)}
function parentGate(){shell(`<section class="card"><h2>🔒 Parent Access</h2><label>Parent PIN</label><input id="pin" type="password" inputmode="numeric"><button class="btn" onclick="checkPin()">Open Dashboard</button><button class="btn secondary" onclick="home()">Cancel</button><p class="small">V1 default PIN: 2468. Change it inside the dashboard.</p></section>`)}
function checkPin(){if($('#pin').value===S.pin)dashboard();else alert('Incorrect PIN')}
function dashboard(){let metrics=Object.entries(S.skills).sort((a,b)=>a[1]-b[1]);let strong=metrics.slice(-2).map(x=>x[0]).join(', '), weak=metrics.slice(0,2).map(x=>x[0]).join(', ');shell(`<section class="hero"><h1>Parent Dashboard</h1><p class="sub">Intervention Day ${S.day} • ${S.history.length} completed sessions</p></section><section class="card"><h2>Reading Skill Profile</h2>${metrics.map(([k,v])=>`<div class="metric"><div class="metricline"><b>${k.replace(/^./,c=>c.toUpperCase())}</b><span>${v}/100</span></div><div class="bar"><i style="width:${v}%"></i></div></div>`).join('')}</section><section class="card"><h2>Instructional Intelligence</h2><p><b>Current strengths:</b> ${strong}</p><p><b>Priority weaknesses:</b> ${weak}</p><p><b>Next-session priority:</b> ${weakest()}</p><p class="small">Scores are V1 instructional mastery indices, not standardized test scores or diagnoses.</p><button class="btn" onclick="copyReport()">📋 Copy Report for ChatGPT</button></section><section class="card"><h2>Settings</h2><label>Change Parent PIN</label><input id="newpin" value="${S.pin}"><button class="btn secondary" onclick="changePin()">Save PIN</button><button class="btn warn" onclick="resetApp()">Reset All Reading Data</button><button class="btn secondary" onclick="home()">Exit Parent Mode</button></section>`)}
function copyReport(){let first=S.history[0]?.skills||S.skills,last=S.skills;let lines=['READING ADVENTURE V1 — PARENT PROGRESS REPORT',`Intervention day: ${S.day}`,`Sessions completed: ${S.history.length}`,'',...Object.keys(S.skills).map(k=>`${k}: ${first[k]} → ${last[k]}`),'',`Current strongest areas: ${Object.entries(S.skills).sort((a,b)=>b[1]-a[1]).slice(0,2).map(x=>x[0]).join(', ')}`,`Current priority weaknesses: ${Object.entries(S.skills).sort((a,b)=>a[1]-b[1]).slice(0,2).map(x=>x[0]).join(', ')}`,`Next-session priority: ${weakest()}`,'','Please analyze this Reading Adventure report, identify patterns/plateaus, and recommend specific changes to the app intervention logic.'];navigator.clipboard.writeText(lines.join('\n')).then(()=>alert('Report copied. Paste it into ChatGPT.'))}
function changePin(){let p=$('#newpin').value.trim();if(p.length<4)return alert('Use at least 4 digits.');S.pin=p;save();alert('PIN saved.')}
function resetApp(){if(confirm('Erase all benchmark and progress data?')){S=structuredClone(DEFAULT);save();home()}}
home();
