const KEY='readingAdventureFamilyV3';
const MAX_KIDS=4;
const SKILLS=['decoding','morphology','vocabulary','literal','inference','gist'];
const labels={decoding:'Decoding',morphology:'Word Parts',vocabulary:'Vocabulary',literal:'Literal Comprehension',inference:'Inference',gist:'Main Idea / Gist',fluency:'Fluency / Pace'};
const AVATARS=['🦊','🐼','🦄','🐯','🐬','🦉','🐲','🦋'];
const INTERESTS=['animals','science','mysteries','space','sports','history','ocean','inventions'];
function freshSkills(){let x={};[...SKILLS,'fluency'].forEach(k=>x[k]={mastery:50,observations:0,recent:[],errors:{},confidence:'low'});return x}
function freshChild(name='Reader',grade=4,avatar='🦊',mode='standard',interests=['animals','science','mysteries']){return {id:'kid_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),name,grade:+grade,avatar,mode,interests,benchmarked:false,day:0,xp:0,streak:0,history:[],seen:{},skills:freshSkills(),fluency:{paceSamples:[]},active:null,created:new Date().toISOString()}}
function freshFamily(){return {version:3,pin:'2468',children:[],activeChildId:null}}
let F;try{F=JSON.parse(localStorage.getItem(KEY))||freshFamily()}catch{F=freshFamily()}if(F.version!==3||!Array.isArray(F.children))F=freshFamily();
let C=null,run=null;const $=s=>document.querySelector(s);const save=()=>localStorage.setItem(KEY,JSON.stringify(F));
function shell(h){$('#app').innerHTML=`<div class="wrap">${h}</div>`}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function selectChild(id){F.activeChildId=id;C=F.children.find(x=>x.id===id)||null;save();home()}
function current(){C=F.children.find(x=>x.id===F.activeChildId)||null;return C}
function score(k){return C?.skills?.[k]?.mastery??50}
function gradeBand(){return `Grade ${C.grade}`}
function modeLabel(){return C.mode==='accelerated'?'Accelerated Intervention':'Adaptive Growth'}
const ITEMS=[
{id:'d1',s:'decoding',d:1,q:'Which word has 3 syllables?',o:['basket','remember','plant','shine'],a:1,why:'Remember has three spoken syllables: re-mem-ber.',e:'syllable_count'},
{id:'d2',s:'decoding',d:2,q:'Choose the best syllable split for fantastic.',o:['fan-tas-tic','fant-ast-ic','fa-ntas-tic'],a:0,why:'Fantastic can be divided fan-tas-tic.',e:'syllable_division'},
{id:'d3',s:'decoding',d:1,q:'Which word can be decoded as re + play?',o:['reply','replay','really'],a:1,why:'Replay contains the prefix re- plus the base word play.',e:'prefix_boundary'},
{id:'d4',s:'decoding',d:2,q:'Which word has a consonant-le ending?',o:['table','rapid','music'],a:0,why:'Table ends in the consonant-le syllable -ble.',e:'syllable_type'},
{id:'d5',s:'decoding',d:2,q:'Which word contains an r-controlled syllable?',o:['market','silent','paper'],a:0,why:'The ar in market is r-controlled.',e:'r_controlled'},
{id:'d6',s:'decoding',d:3,q:'Choose the best way to break apart transportation.',o:['trans-port-a-tion','tran-spor-tation','transp-ort-ation'],a:0,why:'Recognizing meaningful and pronounceable chunks helps: trans-port-a-tion.',e:'multisyllabic'},
{id:'d7',s:'decoding',d:3,q:'Which chunk helps you read unbelievable?',o:['un + believe + able','unb + elie + vable','unbe + liev + able'],a:0,why:'Prefix + base + suffix gives un + believe + able.',e:'morpheme_chunking'},
{id:'d8',s:'decoding',d:2,q:'Which word has four syllables?',o:['dangerous','information','basketball'],a:1,why:'Information has four syllables: in-for-ma-tion.',e:'syllable_count'},
{id:'m1',s:'morphology',d:1,q:'What does the prefix un- usually mean?',o:['again','not','before'],a:1,why:'The prefix un- commonly means not or the opposite of.',e:'prefix_meaning'},
{id:'m2',s:'morphology',d:1,q:'In disagreement, which part means “not/opposite”?',o:['dis-','agree','-ment'],a:0,why:'The prefix dis- can signal not, opposite, or apart.',e:'prefix_meaning'},
{id:'m3',s:'morphology',d:1,q:'What does -less mean in fearless?',o:['full of','without','again'],a:1,why:'The suffix -less means without.',e:'suffix_meaning'},
{id:'m4',s:'morphology',d:2,q:'If re- means again, what does reconsider most nearly mean?',o:['consider again','refuse to consider','consider before'],a:0,why:'Re- + consider means consider again.',e:'morpheme_application'},
{id:'m5',s:'morphology',d:2,q:'The root spect means “look.” What does inspect most nearly mean?',o:['look into closely','write quickly','move away'],a:0,why:'Inspect means to look into or examine closely.',e:'root_meaning'},
{id:'m6',s:'morphology',d:3,q:'Knowing bio means “life” helps you understand biography as…',o:['a written account of a life','a study of rocks','a map of a place'],a:0,why:'Bio relates to life; biography is an account of a person’s life.',e:'root_meaning'},
{id:'v1',s:'vocabulary',d:1,q:'If a trail is treacherous, it is probably…',o:['dangerous','tiny','famous'],a:0,why:'Treacherous means dangerous or hazardous.',e:'word_meaning'},
{id:'v2',s:'vocabulary',d:1,q:'A reluctant person is…',o:['eager','unwilling','noisy'],a:1,why:'Reluctant means hesitant or unwilling.',e:'word_meaning'},
{id:'v3',s:'vocabulary',d:1,q:'If something is scarce, there is…',o:['plenty','very little','exactly enough'],a:1,why:'Scarce means in short supply.',e:'word_meaning'},
{id:'v4',s:'vocabulary',d:2,q:'The scientist made a meticulous drawing. Meticulous most nearly means…',o:['careless','very detailed and careful','unfinished'],a:1,why:'Context suggests the drawing was made with great care and detail.',e:'context_clue'},
{id:'v5',s:'vocabulary',d:2,q:'After the long drought, the rain was beneficial to crops. Beneficial means…',o:['helpful','harmful','unexpected'],a:0,why:'Beneficial means producing a good or helpful result.',e:'context_clue'},
{id:'v6',s:'vocabulary',d:3,q:'The crowd began to disperse after the game. Disperse means…',o:['gather tightly','spread out and leave','cheer loudly'],a:1,why:'To disperse is to scatter or spread out.',e:'academic_vocab'},
{id:'l1',s:'literal',d:1,q:'Maya packed a flashlight before entering the cave. What did Maya pack?',o:['a rope','a flashlight','a map'],a:1,why:'The sentence directly states that Maya packed a flashlight.',e:'detail'},
{id:'l2',s:'literal',d:1,q:'The library closes at six on Fridays. When does it close on Friday?',o:['five','six','seven'],a:1,why:'The detail is stated directly: six.',e:'detail'},
{id:'l3',s:'literal',d:2,q:'Jordan planted tomatoes in April and harvested them in July. What did Jordan plant?',o:['tomatoes','beans','corn'],a:0,why:'The sentence explicitly names tomatoes.',e:'detail'},
{id:'l4',s:'literal',d:2,q:'A solar eclipse occurs when the Moon moves between Earth and the Sun. What moves between Earth and the Sun?',o:['Mars','the Moon','a cloud'],a:1,why:'The sentence directly identifies the Moon.',e:'detail'},
{id:'i1',s:'inference',d:1,q:'Leo kept looking at the dark clouds and hurried to bring the bikes inside. What can you infer?',o:['He expects rain','He lost a bike','He wants to ride'],a:0,why:'Dark clouds plus bringing bikes inside are clues that Leo expects rain.',e:'inference_evidence'},
{id:'i2',s:'inference',d:2,q:'Nia entered the kitchen, smelled smoke, and quickly turned off the oven. What is most likely true?',o:['Something may be burning','She is going outside','The oven is broken'],a:0,why:'The smoke smell and her immediate action support the inference that food may be burning.',e:'inference_evidence'},
{id:'i3',s:'inference',d:2,q:'Caleb whispered and pointed toward a sleeping baby. Why did he probably whisper?',o:['He had a sore throat','He did not want to wake the baby','He forgot how to speak loudly'],a:1,why:'The sleeping baby is evidence that Caleb is trying not to wake the baby.',e:'cause_inference'},
{id:'i4',s:'inference',d:3,q:'The sidewalk glittered, and Mara took tiny steps while gripping the railing. What can you infer?',o:['The sidewalk may be icy','Mara is racing','It is very hot'],a:0,why:'Glittering pavement, tiny steps, and gripping a railing suggest slippery ice.',e:'multiple_clues'},
{id:'g1',s:'gist',d:1,q:'Bees carry pollen between flowers. This helps many plants make seeds and fruit. What is the gist?',o:['Bees help plants reproduce','Bees eat fruit','Flowers avoid bees'],a:0,why:'Both sentences explain how bees help plants reproduce.',e:'gist'},
{id:'g2',s:'gist',d:2,q:'Octopuses can change color to hide. They can squeeze into tiny spaces and release ink to escape predators. What is the gist?',o:['Octopuses have several ways to protect themselves','Octopuses are always black','Predators never find octopuses'],a:0,why:'All details describe ways octopuses protect themselves.',e:'gist'},
{id:'g3',s:'gist',d:2,q:'Trees cool neighborhoods by providing shade. Their leaves also release water vapor that cools the air. What is the gist?',o:['Trees can help keep places cooler','Trees need a lot of water','Shade makes leaves grow'],a:0,why:'Both details explain how trees cool their surroundings.',e:'gist'},
{id:'g4',s:'gist',d:3,q:'Early maps were drawn by hand and often contained mistakes. Modern maps can use satellites to show locations with great precision. What is the gist?',o:['Mapmaking has become more accurate over time','Old maps were always useless','Satellites are difficult to draw'],a:0,why:'The passage contrasts less accurate early maps with precise modern maps.',e:'compare_gist'}];
const PASSAGES=[
{id:'p1',title:'The Secret Language of Honeybees',text:'When a honeybee discovers a rich patch of flowers, it can return to the hive and perform a waggle dance. The direction of the dance gives other bees information about where the flowers are located. The length and energy of the dance can also help communicate distance and quality. This remarkable behavior allows a colony to share information without using spoken language. Scientists have studied the dance for decades because it reveals how animals can communicate complex information through movement.',qs:[['Why does a bee perform a waggle dance?',['To tell other bees where food is','To cool the hive','To scare predators'],0,'literal'],['What is the main idea?',['Bees communicate useful information through movement','All bees dance constantly','Flowers communicate with bees'],0,'gist'],['Why are scientists interested in the dance?',['It shows complex animal communication','It makes honey sweeter','It predicts storms'],0,'inference']]},
{id:'p2',title:'A City Under the Sand',text:'Archaeologists sometimes use satellite images to locate traces of ancient settlements that are difficult to see from the ground. Differences in soil, plant growth, or the shape of the land can reveal where walls and roads once stood. Researchers then compare the images with maps and carefully investigate promising locations. Technology does not replace excavation, but it can help archaeologists decide where to look and reduce unnecessary digging.',qs:[['What can satellite images reveal?',['Possible traces of old walls and roads','The exact age of every artifact','What ancient people sounded like'],0,'literal'],['What is the gist?',['Technology can help archaeologists choose where to investigate','Archaeologists no longer dig','Plants destroy all ancient cities'],0,'gist'],['Why might satellite images reduce unnecessary digging?',['They help identify promising locations first','They make shovels stronger','They remove soil automatically'],0,'inference']]},
{id:'p3',title:'Why Some Animals Glow',text:'In the deep ocean, sunlight disappears quickly. Yet some animals create their own light through a process called bioluminescence. An anglerfish can use a glowing lure to attract prey. Other creatures flash light to confuse predators or communicate with members of their species. Because light is scarce in the deep sea, producing it can provide an important survival advantage.',qs:[['What process lets some animals make light?',['bioluminescence','evaporation','migration'],0,'literal'],['What is the main idea?',['Deep-sea animals use self-made light in several useful ways','All ocean animals glow','Sunlight is strongest deep underwater'],0,'gist'],['Why can producing light be an advantage in deep water?',['Natural light is scarce there','The water is always warm','Predators cannot swim'],0,'inference']]}
];

function landing(){C=null;let kids=F.children;shell(`<section class="hero"><div class="word">📚✨</div><h1>Reading Adventure</h1><p class="sub">Choose who's reading today.</p></section><section class="card"><div class="profilegrid">${kids.map(k=>`<button class="profile" onclick="selectChild('${k.id}')"><span class="avatar">${k.avatar}</span><b>${esc(k.name)}</b><small>Grade ${k.grade}${k.mode==='accelerated'?' • Accelerated':''}</small></button>`).join('')}${kids.length<MAX_KIDS?`<button class="profile add" onclick="addChildForm()"><span class="avatar">＋</span><b>Add Reader</b><small>Up to ${MAX_KIDS} children</small></button>`:''}</div><button class="btn secondary" onclick="parentGate()">🔒 Parent Dashboard</button></section>`)}
function addChildForm(editId=''){let k=editId?F.children.find(x=>x.id===editId):null;shell(`<section class="card"><h2>${k?'Edit Reader':'Add a Reader'}</h2><label>Name or nickname</label><input id="kidname" maxlength="20" value="${esc(k?.name||'')}"><label>School grade</label><select id="kidgrade">${[2,3,4,5,6].map(g=>`<option ${(+k?.grade||4)===g?'selected':''}>${g}</option>`).join('')}</select><label>Learning plan</label><select id="kidmode"><option value="standard" ${k?.mode!=='accelerated'?'selected':''}>Adaptive Growth</option><option value="accelerated" ${k?.mode==='accelerated'?'selected':''}>Accelerated Intervention</option></select><p class="small">Accelerated Intervention gives more daily weight to prerequisite gaps and retests transfer/retention more often. It does not skip mastery checks.</p><label>Avatar</label><div class="avatarrow">${AVATARS.map((a,i)=>`<label class="avatarpick"><input type="radio" name="avatar" value="${a}" ${(k?.avatar||'🦊')===a?'checked':''}><span>${a}</span></label>`).join('')}</div><label>Interests (choose any)</label><div class="chips">${INTERESTS.map(x=>`<label class="chip"><input type="checkbox" name="interest" value="${x}" ${(k?.interests||['animals','science','mysteries']).includes(x)?'checked':''}> ${x}</label>`).join('')}</div><button class="btn" onclick="saveChild('${editId}')">${k?'Save Changes':'Create Reader'}</button><button class="btn secondary" onclick="${editId?'dashboard(\''+editId+'\')':'landing()'}">Cancel</button></section>`)}
function saveChild(editId=''){let name=$('#kidname').value.trim();if(!name)return alert('Enter a name or nickname.');let grade=+$('#kidgrade').value,mode=$('#kidmode').value,avatar=document.querySelector('input[name=avatar]:checked')?.value||'🦊',interests=[...document.querySelectorAll('input[name=interest]:checked')].map(x=>x.value);if(!interests.length)interests=['animals'];if(editId){let k=F.children.find(x=>x.id===editId);Object.assign(k,{name,grade,mode,avatar,interests})}else{if(F.children.length>=MAX_KIDS)return alert('Reading Adventure supports up to four children.');F.children.push(freshChild(name,grade,avatar,mode,interests))}save();landing()}
function home(){if(!current())return landing();let b=C.benchmarked;shell(`<section class="hero"><div class="topline"><button class="exit" onclick="landing()">← Switch Reader</button><span class="tag">${gradeBand()}</span></div><div class="word">${C.avatar}</div><h1>${esc(C.name)}'s Adventure</h1><p class="sub">${modeLabel()} • Build stronger reading powers one mission at a time.</p>${!b?`<button class="btn" onclick="benchmarkIntro()">Start My Reading Power Check</button>`:`<button class="btn" onclick="startDaily()">▶ Start Today's Mission</button><button class="btn secondary" onclick="startPractice()">🎯 Practice Zone</button>`}<button class="btn secondary" onclick="parentGate()">🔒 Parent Dashboard</button></section>${b?`<section class="card"><div class="grid"><div class="stat"><span>Mission Days</span><b>${C.day}</b></div><div class="stat"><span>XP</span><b>${C.xp}</b></div><div class="stat"><span>Streak</span><b>${C.streak}</b></div><div class="stat"><span>Focus</span><b style="font-size:1rem">${labels[weakest()]}</b></div></div></section>`:''}`)}
function benchmarkIntro(){shell(`<section class="hero"><h1>Reading Power Check</h1><p class="sub">This check finds where instruction should begin for ${esc(C.name)}. Questions sample skills around Grade ${C.grade} and foundational skills below it when needed.</p><div class="notice">This is an instructional benchmark, not a diagnosis or standardized state test.</div><button class="btn" onclick="startBenchmark()">I'm Ready</button><button class="btn secondary" onclick="home()">Not Yet</button></section>`)}
function pickBenchmark(){let out=[];SKILLS.forEach(s=>{let a=ITEMS.filter(x=>x.s===s);out.push(...a.slice(0,Math.min(C.mode==='accelerated'?5:4,a.length)))});return shuffle(out)}
function startBenchmark(){run={type:'benchmark',items:pickBenchmark(),i:0,results:[],started:Date.now()};renderItem()}
function exitRun(){if(!run)return home();if(confirm('Exit this mission? Unfinished work will not count as a completed session.')){run=null;C.active=null;save();home()}}
function renderItem(){if(run.i>=run.items.length)return run.type==='benchmark'?finishBenchmark():finishDaily();let x=run.items[run.i];run.shownAt=performance.now();shell(`<section class="card"><div class="topline"><div><div class="phase">${run.type==='benchmark'?'Power Check':run.phase||'Skill Training'}</div><div class="small">${run.i+1}/${run.items.length}</div></div><button class="exit" onclick="exitRun()">← Exit</button></div><div class="bar"><i style="width:${100*run.i/run.items.length}%"></i></div><h2>${x.q}</h2>${x.o.map((o,j)=>`<button class="btn choice" onclick="respond(${j})">${o}</button>`).join('')}</section>`)}
function respond(choice){let x=run.items[run.i],ok=choice===x.a,ms=Math.round(performance.now()-run.shownAt);run.results.push({id:x.id,skill:x.s,ok,error:ok?null:x.e,ms,d:x.d});if(run.type==='benchmark'){run.i++;return renderItem()}shell(`<section class="card"><div class="topline"><div class="phase">Feedback</div><button class="exit" onclick="exitRun()">← Exit</button></div><div class="feedback ${ok?'ok':'no'}"><h2>${ok?'✓ Nice work':'Not yet — learn from it'}</h2><p>${x.why}</p></div><button class="btn" onclick="nextItem()">Continue</button></section>`)}
function nextItem(){run.i++;renderItem()}
function updateSkill(k,rs,weight=1){if(!rs.length)return;let sk=C.skills[k],correct=rs.filter(r=>r.ok).length,p=correct/rs.length,avgD=rs.reduce((a,r)=>a+r.d,0)/rs.length,target=Math.round(25+20*avgD+35*p);let alpha=Math.min(.42,.12+.035*rs.length)*weight;sk.mastery=Math.round(sk.mastery*(1-alpha)+target*alpha);sk.observations+=rs.length;sk.recent=[...sk.recent,...rs.map(r=>r.ok?1:0)].slice(-20);rs.filter(r=>r.error).forEach(r=>sk.errors[r.error]=(sk.errors[r.error]||0)+1);sk.confidence=sk.observations>=20?'high':sk.observations>=8?'medium':'low'}
function finishBenchmark(){SKILLS.forEach(k=>updateSkill(k,run.results.filter(r=>r.skill===k),1.4));C.skills.fluency.mastery=50;C.benchmarked=true;C.baseline=Object.fromEntries(Object.entries(C.skills).map(([k,v])=>[k,v.mastery]));C.benchmarkDate=new Date().toISOString();save();run=null;shell(`<section class="hero"><h1>Power Check Complete 🎉</h1><p class="sub">I found ${esc(C.name)}'s starting point. Daily missions will teach, practice, and keep measuring what changes.</p><button class="btn" onclick="home()">See My Adventure</button></section>`)}
function weakest(){return SKILLS.slice().sort((a,b)=>score(a)-score(b))[0]}
function unseenFor(skill,n){let all=ITEMS.filter(x=>x.s===skill).sort((a,b)=>Math.abs((25+20*x.d)-score(skill))-Math.abs((25+20*b.d)-score(skill)));let fresh=all.filter(x=>!(C.seen[x.id]>=(C.day-(C.mode==='accelerated'?4:2))));let pool=fresh.length>=n?fresh:all;return shuffle(pool).slice(0,n)}
function buildDaily(){let ranked=SKILLS.slice().sort((a,b)=>score(a)-score(b)),items=[];if(C.mode==='accelerated')items.push(...unseenFor(ranked[0],6),...unseenFor(ranked[1],4),...unseenFor(ranked[2],3));else items.push(...unseenFor(ranked[0],4),...unseenFor(ranked[1],3),...unseenFor(ranked[2],2));let probe=C.day>0&&(C.day+1)%5===0;if(probe)SKILLS.forEach(k=>items.push(...unseenFor(k,1)));return {items:shuffle(items),probe}}
function startDaily(){let b=buildDaily();run={type:'daily',phase:b.probe?'Weekly Check + Training':C.mode==='accelerated'?'Accelerated Skill Training':'Skill Training',items:b.items,i:0,results:[],started:Date.now(),probe:b.probe};C.active={started:new Date().toISOString()};save();renderItem()}
function startPractice(){let k=weakest();run={type:'daily',phase:'Practice Zone',items:unseenFor(k,6),i:0,results:[],started:Date.now(),probe:false,practice:true};renderItem()}
function finishDaily(){run.results.forEach(r=>C.seen[r.id]=C.day);SKILLS.forEach(k=>updateSkill(k,run.results.filter(r=>r.skill===k),run.practice?.45:1));let correct=run.results.filter(r=>r.ok).length,pct=Math.round(100*correct/run.results.length),minutes=Math.max(1,Math.round((Date.now()-run.started)/60000));if(run.practice){run=null;save();return shell(`<section class="hero"><h1>Practice Complete 🎯</h1><div class="word">${pct}%</div><p class="sub">Practice reinforced ${labels[weakest()]}. It has reduced weight in the progress model so extra practice cannot artificially inflate growth.</p><button class="btn" onclick="home()">Finish</button></section>`)}C.day++;C.xp+=correct*10;C.streak=pct>=70?C.streak+1:0;C.history.push({date:new Date().toISOString(),day:C.day,pct,minutes,skills:Object.fromEntries(Object.entries(C.skills).map(([k,v])=>[k,v.mastery])),errors:run.results.filter(r=>r.error).map(r=>r.error),probe:run.probe});C.active=null;save();run=null;shell(`<section class="hero"><h1>Skill Training Complete 🚀</h1><div class="word">${pct}%</div><p>You earned <b>${correct*10} XP</b>.</p><p class="sub">Finish with connected reading to build comprehension and reading pace.</p><button class="btn" onclick="startPassage()">Open Reading Challenge</button><button class="btn secondary" onclick="home()">Finish for Now</button></section>`)}
function choosePassage(){return PASSAGES[(C.day+C.grade)%PASSAGES.length]}
function startPassage(preview=false){let p=choosePassage();run={type:'passage',passage:p,preview,started:null};shell(`<section class="card"><div class="topline"><div><div class="phase">Reading Challenge</div><div class="small">${p.title}</div></div><button class="exit" onclick="${preview?'dashboard(\''+C.id+'\')':'exitPassage()'}">← Exit</button></div><p class="sub">Read this passage aloud at a comfortable pace. Tap Start, read the whole passage, then tap Finished.</p><button class="btn" onclick="beginTimedRead()">Start Reading</button></section>`)}
function beginTimedRead(){run.started=performance.now();let p=run.passage;shell(`<section class="card"><div class="topline"><div class="phase">Read Aloud</div><button class="exit" onclick="exitPassage()">← Exit</button></div><h2>${p.title}</h2><div class="passage">${p.text}</div><button class="btn" onclick="finishTimedRead()">Finished Reading</button></section>`)}
function finishTimedRead(){let sec=Math.max(10,(performance.now()-run.started)/1000),words=run.passage.text.trim().split(/\s+/).length,wpm=Math.round(words/(sec/60));run.wpm=wpm;run.qi=0;run.pres=[];renderPassageQ()}
function renderPassageQ(){let p=run.passage;if(run.qi>=p.qs.length)return finishPassage();let [q,o,a,s]=p.qs[run.qi];shell(`<section class="card"><div class="topline"><div class="phase">Understand What You Read</div><button class="exit" onclick="exitPassage()">← Exit</button></div><h2>${q}</h2>${o.map((z,j)=>`<button class="btn choice" onclick="answerPassage(${j},${a},'${s}')">${z}</button>`).join('')}</section>`)}
function answerPassage(j,a,s){run.pres.push({skill:s,ok:j===a,d:2,error:j===a?null:'connected_text_'+s});run.qi++;renderPassageQ()}
function finishPassage(){let comprehension=Math.round(100*run.pres.filter(x=>x.ok).length/run.pres.length),preview=run.preview,w=run.wpm;if(!preview){run.pres.forEach(r=>updateSkill(r.skill,[r],.6));C.fluency.paceSamples.push({date:new Date().toISOString(),wpm:w,comprehension});C.fluency.paceSamples=C.fluency.paceSamples.slice(-20);if(comprehension>=67){let target=Math.max(30,Math.min(90,35+(w-70)*.35));C.skills.fluency.mastery=Math.round(.8*C.skills.fluency.mastery+.2*target);C.skills.fluency.observations++;}save()}run=null;shell(`<section class="hero"><h1>Reading Challenge Complete 📖</h1><p><b>Reading pace estimate:</b> ${w} words/minute</p><p class="sub">This is a browser timing estimate, not a standardized oral-reading-fluency/WCPM score because the app does not independently score oral reading errors or prosody.</p><button class="btn" onclick="${preview?'dashboard(\''+C.id+'\')':'home()'}">Finish</button></section>`)}
function exitPassage(){if(confirm('Exit this reading challenge? Incomplete results will not be saved.')){run=null;home()}}
function parentGate(){shell(`<section class="card"><h2>🔒 Parent Access</h2><label>Parent PIN</label><input id="pin" type="password" inputmode="numeric"><button class="btn" onclick="checkPin()">Open Dashboard</button><button class="btn secondary" onclick="${C?'home()':'landing()'}">Cancel</button><p class="small">Default PIN: 2468</p></section>`)}
function checkPin(){if($('#pin').value===F.pin)dashboard(C?.id||'');else alert('Incorrect PIN')}
function familyDashboard(){shell(`<section class="hero"><h1>Parent Dashboard</h1><p class="sub">Family overview • ${F.children.length}/${MAX_KIDS} reader profiles</p></section><section class="card"><h2>Readers</h2>${F.children.map(k=>`<button class="btn secondary" onclick="dashboard('${k.id}')">${k.avatar} ${esc(k.name)} • Grade ${k.grade} • Day ${k.day}${k.mode==='accelerated'?' • Accelerated':''}</button>`).join('')}${F.children.length<MAX_KIDS?`<button class="btn" onclick="addChildForm()">＋ Add Reader</button>`:''}</section><section class="card"><h2>Family Data</h2><button class="btn secondary" onclick="exportFamily()">💾 Back Up All Children</button><label>Restore Family Backup</label><input id="restoreFamily" type="file" accept="application/json"><button class="btn secondary" onclick="restoreFamily()">📥 Restore Backup</button><label>Change Parent PIN</label><input id="newpin" value="${F.pin}" inputmode="numeric"><button class="btn secondary" onclick="changePin()">Save PIN</button><button class="btn warn" onclick="factoryReset()">Factory Reset Everything</button><button class="btn secondary" onclick="landing()">Exit Parent Mode</button></section>`)}
function topErrors(){let e={};SKILLS.forEach(k=>Object.entries(C.skills[k].errors||{}).forEach(([x,n])=>e[x]=(e[x]||0)+n));return Object.entries(e).sort((a,b)=>b[1]-a[1]).slice(0,4)}
function trend(k){let h=C.history;if(h.length<3)return 'Not enough data';let a=h.slice(-3).map(x=>x.skills[k]??score(k));let d=a[a.length-1]-a[0];return d>=4?'Improving ↑':d<=-4?'Needs review ↓':'Stable →'}
function dashboard(id=''){if(!id)return familyDashboard();F.activeChildId=id;current();let metrics=[...SKILLS,'fluency'].sort((a,b)=>score(a)-score(b)),strong=metrics.slice(-2),weak=metrics.slice(0,2),errs=topErrors(),pace=C.fluency.paceSamples.at(-1);shell(`<section class="hero"><div class="word">${C.avatar}</div><h1>${esc(C.name)}</h1><p class="sub">Grade ${C.grade} • ${modeLabel()} • Intervention Day ${C.day}</p></section><section class="card"><button class="btn secondary" onclick="familyDashboard()">← All Readers</button><button class="btn secondary" onclick="addChildForm('${C.id}')">✏️ Edit Profile</button></section><section class="card"><h2>Reading Skill Profile</h2>${metrics.map(k=>`<div class="metric"><div class="metricline"><b>${labels[k]}</b><span>${score(k)}/100 • ${C.skills[k].confidence}</span></div><div class="bar"><i style="width:${score(k)}%"></i></div><div class="mini">${C.skills[k].observations} observations • ${trend(k)}</div></div>`).join('')}<p class="small">Instructional mastery estimates are app measures, not standardized scores or grade-equivalent scores.</p></section><section class="card"><h2>Instructional Intelligence</h2><p><b>Relative strengths:</b> ${strong.map(k=>labels[k]).join(', ')}</p><p><b>Priority weaknesses:</b> ${weak.map(k=>labels[k]).join(', ')}</p><p><b>Next-session priority:</b> ${labels[weakest()]}</p>${errs.length?`<p><b>Most frequent error patterns:</b> ${errs.map(([e,n])=>`${e.replaceAll('_',' ')} (${n})`).join(', ')}</p>`:''}${pace?`<p><b>Latest reading pace estimate:</b> ${pace.wpm} wpm with ${pace.comprehension}% passage comprehension</p>`:''}<button class="btn" onclick="copyReport()">📋 Copy Report for ChatGPT</button><button class="btn secondary" onclick="previewMission()">👀 Preview Today's Mission</button></section><section class="card"><h2>${esc(C.name)}'s Data & Safety</h2><button class="btn secondary" onclick="exportChild()">💾 Export This Child</button><label>Restore Child Backup</label><input id="restoreChild" type="file" accept="application/json"><button class="btn secondary" onclick="restoreChild()">📥 Restore Child Backup</button><button class="btn warn" onclick="resetProgress()">Reset This Child's Progress</button><button class="btn warn" onclick="removeChild()">Remove This Child</button><button class="btn secondary" onclick="familyDashboard()">Back to Family Dashboard</button></section>`)}
function previewMission(){let b=buildDaily();shell(`<section class="card"><h2>${esc(C.name)}'s Mission Preview</h2><p class="sub">Preview mode does not affect scores.</p><p><b>Plan:</b> ${modeLabel()}</p><p><b>Primary focus:</b> ${labels[weakest()]}</p><p><b>Skill questions:</b> ${b.items.length}</p><p><b>Weekly probe:</b> ${b.probe?'Yes':'No'}</p><button class="btn secondary" onclick="startPassage(true)">Preview Reading Passage</button><button class="btn" onclick="dashboard('${C.id}')">Back</button></section>`)}
function copyReport(){let base=C.baseline||Object.fromEntries(Object.keys(C.skills).map(k=>[k,50])),errs=topErrors();let lines=['READING ADVENTURE FAMILY V3 — PARENT PROGRESS REPORT',`Child: ${C.name}`,`Enrolled grade: ${C.grade}`,`Plan: ${modeLabel()}`,`Intervention day: ${C.day}`,`Completed sessions: ${C.history.length}`,'',...Object.keys(C.skills).map(k=>`${labels[k]}: ${base[k]??50} → ${score(k)} | observations ${C.skills[k].observations} | confidence ${C.skills[k].confidence} | trend ${trend(k)}`),'',`Priority: ${labels[weakest()]}`,`Frequent error patterns: ${errs.map(([e,n])=>`${e}:${n}`).join(', ')||'none yet'}`,`Reading pace samples: ${C.fluency.paceSamples.map(x=>`${x.wpm}wpm/${x.comprehension}%comp`).join(', ')||'none yet'}`,'','Analyze this child’s trajectory and error patterns. Recommend specific changes to Reading Adventure intervention allocation, prerequisite skills, or item difficulty. The primary goal for an Accelerated Intervention profile is rapid catch-up toward the enrolled grade while verifying retention and transfer. Do not treat app mastery indices or pace estimates as standardized test scores.'];navigator.clipboard.writeText(lines.join('\n')).then(()=>alert('Report copied. Paste it into ChatGPT.'))}
function changePin(){let p=$('#newpin').value.trim();if(!/^\d{4,}$/.test(p))return alert('Use at least 4 digits.');F.pin=p;save();alert('PIN saved.')}
function resetProgress(){if(!confirm(`Reset ${C.name}'s benchmark, XP, sessions, skill history, and reading progress? Other children will not be affected.`))return;if(!confirm('This cannot be undone unless you exported a backup. Reset now?'))return;let old=C,n=freshChild(old.name,old.grade,old.avatar,old.mode,old.interests);n.id=old.id;let i=F.children.findIndex(x=>x.id===old.id);F.children[i]=n;C=n;save();dashboard(C.id)}
function removeChild(){if(!confirm(`Remove ${C.name} and all of this child's reading data?`))return;if(!confirm('Final warning: this cannot be undone without a backup.'))return;F.children=F.children.filter(x=>x.id!==C.id);F.activeChildId=null;save();familyDashboard()}
function factoryReset(){if(!confirm('Factory reset EVERYTHING, including all children, parent PIN, and progress?'))return;if(!confirm('Final warning: this erases all Reading Adventure data on this device.'))return;F=freshFamily();C=null;save();landing()}
function downloadJSON(obj,name){let blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportChild(){downloadJSON({kind:'reading-adventure-child-v3',child:C},`reading-adventure-${C.name.replace(/[^a-z0-9]/gi,'-')}-${new Date().toISOString().slice(0,10)}.json`)}
function exportFamily(){downloadJSON(F,`reading-adventure-family-${new Date().toISOString().slice(0,10)}.json`)}
function restoreChild(){let f=$('#restoreChild').files[0];if(!f)return alert('Choose a child backup first.');let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(x.kind!=='reading-adventure-child-v3'||!x.child?.skills)throw Error();if(confirm(`Replace ${C.name}'s current data with the backup for ${x.child.name}?`)){let id=C.id;x.child.id=id;F.children[F.children.findIndex(k=>k.id===id)]=x.child;C=x.child;save();dashboard(id)}}catch{alert('That is not a valid child backup.')}};r.readAsText(f)}
function restoreFamily(){let f=$('#restoreFamily').files[0];if(!f)return alert('Choose a family backup first.');let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(x.version!==3||!Array.isArray(x.children)||x.children.length>4)throw Error();if(confirm('Replace ALL current family data with this backup?')){F=x;C=null;save();familyDashboard()}}catch{alert('That is not a valid Reading Adventure Family V3 backup.')}};r.readAsText(f)}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
landing();
